Carefully explained the checksum problem.
ioggstream/draft-polli-resource-digests-http pull request #12
Opened 2019-05-07 16:28 UTC by ioggstream

## This PR

Explains why we need requirement for selected representation

## Note

I somewhat repeated part of the introduction to explicitly
clarify the requirement and make this document independent
from the reading of RFC3230

2019-05-07 16:50 UTC, ioggstream commented
Hi @LPardue

here's the artifact for this build. Is that good enough to share it with the others?

- https://19-183264553-gh.circle-artifacts.com/0/tmp/artifacts/draft-polli-resource-digests-http.html#rfc.section.2

Thx++,
R

2019-05-08 22:49 UTC, LPardue requested changes
Minor nits on the range request but other it LGTM!

2019-05-08 22:49 UTC, LPardue commented on draft-polli-resource-digests-http.md
> +A Range-Requests alters the payload body, conveying a partial representation.
```suggestion
A Range-Request alters the payload body, conveying a partial representation.
```

2019-05-08 22:49 UTC, LPardue commented on draft-polli-resource-digests-http.md
> +    Accept-Range: bytes=1-7
```suggestion
    Range: bytes=1-7
```

2019-05-09 19:39 UTC, merged